[package]
name = "gnome-web-apps"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
env_logger = "0"
freedesktop-desktop-entry = "0"
gtk = { version = "*", features = ["v4_8"], package = "gtk4" }
libadwaita = { version = "0", features = ["v1_7"] }
log = "0"
sanitize-filename = "0.6"
scraper = { version = "0", features = ["atomic"] }
ureq = { version = "3.1", features = ["gzip"] }
validator = "0"
xdg = "3"
