name: Ungoogled Chromium
flatpak: io.github.ungoogled_software.ungoogled_chromium
system_bin:
can_isolate: true
desktop_file_name_prefix: io.github.ungoogled_software.ungoogled_chromium.ungoogled_chromium
base: chromium
